project/config/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from django.views import defaults as default_views

from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

# Add the files which shouldn't be internationalized
urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(
        r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'
    ),

    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Markdown processor
    url(r'^markdownx/', include('markdownx.urls')),
]

urlpatterns += i18n_patterns(
    # Examples:
    # url(r'^$', 'nmc_lms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Notice the expression does not end in $,
    # that happens at the myapp/url.py level
    # url(r'^tales/',include('lms_tales.urls', namespace='tales')),
    url(r'^', include('lms_tales.urls', namespace='tales')),
    url(r'^nahtkurs/', include('lms_nahtkurs.urls', namespace='nahtkurs')),
    url(r'^opos/', include('lms_opos.urls', namespace='opos')),
    # Example of redirect to site in specific hard coded language
    # url(r'^opos/', RedirectView.as_view(url='https://tales.nmc.unibas.ch/opos/en/',
    #                                    permanent=False), name='index'),

    # Tales
    url(r'^krank-ohne-ursache/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'krank-ohne-ursache', 'pk': '2'}
                                            )
                             ),
        name='redirect_krank-ohne-ursache'),
    url(r'^erasmus/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'erasmus-von-rotterdam', 'pk': '3'}
                                            )
                             ),
        name='redirect_erasmus'),
    url(r'^linear-algebra-ii/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'linear-algebra-ii', 'pk': '4'}
                                            )
                             ),
        name='redirect_linear-algebra-ii'),
    url(r'^conducting-psychological-research/',
        RedirectView.as_view(
            url=reverse_lazy(
                'tales:course',
                kwargs={'slug': 'conducting-psychological-research', 'pk': '6'}
                                            )
                            ),
        name='conducting-psychological-research'),


    url(r'^entrepreneurship-in-nonprofits/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'entrepreneurship-in-nonprofits', 'pk': '10'}  # NOQA
                                            )
                             ),
        name='redirect_entrepreneurship-in-nonprofits'),
    url(r'^base/', include('lms_base.urls', namespace='base')),

    url(r'^select2/', include('django_select2.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

project/lms_nahtkurs/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import url
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from lms_nahtkurs import views

static_urls = [
    # markdown tutorial
    url(
        r'^markdown$',
        TemplateView.as_view(template_name='markdown.html'),
        name='markdown'
    ),
    url(
        r'^impressum$',
        TemplateView.as_view(template_name='impressum.html',),
        name='impressum'
    ),
    url(
        r'^about$',
        TemplateView.as_view(template_name='pages/nahtkurs_about.html',),
        name='about'
    ),
    url(
        r'^help$',
        TemplateView.as_view(template_name='help.html',),
        name='help'
    ),
    url(
        r'^glossar$',
        TemplateView.as_view(template_name='pages/nahtkurs_glossar.html',),
        name='glossar'
    ),
]

course_urls = [
    # course list
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('nahtkurs:course',
                             kwargs={'slug': 'nahtkurs', 'pk': '2'}
                                            )
                             ),
        name='redirect_nahtkurs'),
    url(
        r'^course/add$',
        views.CourseCreate.as_view(),
        name='course_add'
    ),
    url(
        r'^course/edit/(?P<pk>\d+)$',
        never_cache(views.CourseUpdate.as_view()),
        name='course_edit'
    ),
    url(
        r'^course/delete/(?P<pk>\d+)$',
        views.CourseDelete.as_view(),
        name='course_delete'
    ),
    # course overview / chapter list
    url(
        r'^(?P<slug>[\w-]+)-(?P<pk>\d+)/$',
        views.CourseDetails.as_view(
            template_name='nahtkurs_course_home.html',
            ),
        name='course'
    ),
    url(
        r'^(?P<slug>[\w-]+)-(?P<pk>\d+)/kontakt$',
        views.CourseDetails.as_view(
            template_name='nahtkurs_kontakt.html',
            ),
        name='kontakt'
    ),
]

chapter_urls = [
    url(
        r'^chapter/add/(?P<course_pk>\d+)$',
        views.ChapterCreate.as_view(),
        name='chapter_add'
    ),
    url(
        r'^chapter/edit/(?P<pk>\d+)$',
        never_cache(views.ChapterUpdate.as_view()),
        name='chapter_edit'
    ),
    url(
        r'^chapter/delete/(?P<pk>\d+)$',
        views.ChapterDelete.as_view(),
        name='chapter_delete'
    ),
    # chapter overview / step list
    url(
        r'^(?P<course_slug>[\w-]+)-(?P<course_pk>\d+)/'
        r'(?P<slug>[\w-]+)-(?P<pk>\d+)/$',
        views.ChapterDetails.as_view(
            template_name='nahtkurs_chapter_home.html',
            ),
        name='chapter'
    ),
    url(
        r'^chapter_order$',
        views.chapter_update_order,
        name='chapter_update_order'
    ),
]

step_urls = [
    url(
        r'^step/add/(?P<chapter_pk>\d+)$',
        views.StepCreate.as_view(),
        name='step_add'
    ),
    url(
        r'^step/edit/(?P<pk>\d+)$',
        never_cache(views.StepUpdate.as_view()),
        name='step_edit'
    ),
    url(
        r'^step/delete/(?P<pk>\d+)$',
        views.StepDelete.as_view(),
        name='step_delete'
    ),
    # step
    url(
        r'^(?P<course_slug>[\w-]+)-(?P<course_pk>\d+)/'
        r'(?P<chapter_slug>[\w-]+)-(?P<chapter_pk>\d+)/'
        r'(?P<slug>[\w-]+)-(?P<pk>\d+)$',
        views.StepDetails.as_view(
            template_name='nahtkurs_step_home.html',
            ),
        name='step'
    ),
    url(
        r'^step_order$',
        views.step_update_order,
        name='step_update_order',
    ),
]


urlpatterns = static_urls + course_urls + chapter_urls + step_urls

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^404/$', views.NotFoundView.as_view()),
    ]

project/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

project/lms_nahtkurs/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from lms_base.models import StepMixin, ChapterMixin, CourseMixin


def course_directory_path(instance, filename):
    return '{0}/{1}'.format(instance.course.slug, filename)


class NahtkursStep(StepMixin):  # noqa 405
    chapter = models.ForeignKey(
            'NahtkursChapter', null=True, related_name='steps'
            )

    def get_course(self):
        return self.chapter.course

    def get_absolute_url(self):
        return reverse('nahtkurs:step', args=[str(self.chapter.course.slug),
                                              str(self.chapter.course.id),
                                              str(self.chapter.slug),
                                              str(self.chapter.id),
                                              str(self.slug),
                                              str(self.id), ])

    def get_step_number(self):
        chapter_list = list(self.chapter.course.chapters.all()
                            .order_by('order'))
        chapter_num = str(chapter_list.index(self.chapter) + 1)
        step_list = list(self.chapter.steps.all().order_by('order'))
        step_num = str(step_list.index(self) + 1)
        index = chapter_num + "." + step_num
        return index

    def save(self, *args, **kwargs):
        if not self.chapter.steps.all():
            self.order = 0
        if self.order is None:
            self.order = max(step.order for step in
                             self.chapter.steps.all()) + 1
        super(NahtkursStep, self).save(*args, **kwargs)


def step_directory_path(instance, filename):
    return '{0}/{1}/{2}/{3}'.format(
        instance.step.chapter.course.slug,
        instance.step.chapter.slug,
        instance.step.slug,
        filename)


@python_2_unicode_compatible
class NahtkursStepFile(models.Model):
    title = models.CharField(max_length=70)
    step = models.ForeignKey('NahtkursStep', related_name='files')
    file = models.FileField(upload_to=step_directory_path, max_length=255)

    def __str__(self):
        return self.title


class NahtkursChapter(ChapterMixin):  # noqa 405

    course = models.ForeignKey(
            'NahtkursCourse', null=True, related_name='chapters'
            )

    def get_course(self):
        return self.course

    def get_absolute_url(self):
        return reverse('nahtkurs:chapter', args=[str(self.course.slug),
                                                 str(self.course.id),
                                                 str(self.slug),
                                                 str(self.id), ])

    def save(self, *args, **kwargs):
        if not self.course.chapters.all():
            self.order = 0
        if self.order is None:
            self.order = max(chapter.order for chapter in
                             self.course.chapters.all()) + 1
        super(NahtkursChapter, self).save(*args, **kwargs)


class NahtkursCourse(CourseMixin):  # noqa 405

    def get_course(self):
        return self

    def get_absolute_url(self):
        return reverse('nahtkurs:course', args=[str(self.slug),
                                                str(self.id), ])


@python_2_unicode_compatible
class NahtkursAuthor(models.Model):

    name = models.TextField(max_length=None)
    image = models.ImageField(upload_to=course_directory_path,
                              max_length=255, blank=True, null=True)
    course = models.ForeignKey('NahtkursCourse', related_name='author',
                               verbose_name='author')

    def __str__(self):
        return self.name

project/lms_nahtkurs/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms
from django.forms import ModelForm

from extra_views import InlineFormSet

from lms_nahtkurs import widgets, models


class CourseForm(ModelForm):
    class Meta:
        model = models.NahtkursCourse
        exclude = ['slug', 'owner', ]
        widgets = {
            'content': widgets.CustomisableMarkdownxWidget(),
            'author': widgets.CustomisableMarkdownxWidget(),
            'copyright': widgets.CustomisableMarkdownxWidget(),
            'course_contact': widgets.CustomisableMarkdownxWidget(),
        }


class AuthorInline(InlineFormSet):
    model = models.NahtkursAuthor
    fields = '__all__'
    prefix = 'authors'
    extra = 1


class UpdateCourseForm(CourseForm):
    title_image = forms.ImageField(required=False)


class ChapterForm(ModelForm):
    class Meta:
        model = models.NahtkursChapter
        exclude = ['slug', 'order', 'course', ]
        widgets = {
            'content': widgets.CustomisableMarkdownxWidget(),
        }


class StepForm(ModelForm):
    class Meta:
        model = models.NahtkursStep
        exclude = ['slug', 'order', 'chapter', ]
        widgets = {
            'content': widgets.CustomisableMarkdownxWidget(),
            'copyright': widgets.CustomisableMarkdownxWidget(),
        }


class FilesInline(InlineFormSet):
    model = models.NahtkursStepFile
    fields = ['title', 'file']
    prefix = 'files'
    extra = 1

project/lms_nahtkurs/templates/nahtkurs_chapter_home.html
{% extends "lms_nahtkurs_base.html" %}
{% load i18n rules %}
{% block javascript %}
  {{ block.super }}
  {% if user.is_authenticated %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.5.1/Sortable.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>
  <script src="{{STATIC_URL}}lms_nahtkurs/js/lms_nahtkurs_chapter_home.js"></script>
  {% endif %}
  <script>
    var urlpath = "{% url 'nahtkurs:step_update_order' %}";
    var object_pk = '{{ object.pk }}';
  </script>
{% endblock %}

{% block course-title %}
{% include "nahtkurs_chapter-title.html" %}
{% endblock course-title %}

{% block content %}
{% has_perm 'lms_nahtkurs.change_nahtkursstep' user object.course as can_change %}
{% has_perm 'lms_nahtkurs.delete_nahtkursstep' user object.course as can_delete %}
{% has_perm 'lms_nahtkurs.add_nahtkursstep' user object.course as can_add %}

<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 pt-3">
      <h1 class="chapter-heading">{{ object.title }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-8 offset-md-2">
      <h5>{% trans 'Steps' %}</h5>
        <table class="table table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans 'Titel' %}</th>
              <th>{% trans 'Aktion' %}</th>
            </tr>
          </thead>
          <tbody id="step-list">
          {% for step in object.steps.all %}
          <tr data-id="{{ step.pk }}" class="step-list-item">
            <td>
              <i class="fa fa-bars handle" aria-hidden="true"></i>
            </td>
            <td>
              <a href="{% url 'nahtkurs:step' object.course.slug object.course.pk object.slug object.pk step.slug step.pk %}">
              {{ step.title }}
              </a>
            </td>
            <td>
              {% if user.is_authenticated %}
              {% if can_change %}
              <a href="{% url 'nahtkurs:step_edit' step.pk %}">
                <i class="fa fa-pencil" aria-hidden="true"></i>
                {% trans 'Bearbeiten' %}
              </a>
              {% endif %}
              {% if can_delete %}
              <a href="{% url 'nahtkurs:step_delete' step.pk %}">
                <i class="fa fa-trash" aria-hidden="true"></i>
                {% trans 'Löschen' %}
              </a>
              {% endif %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if user.is_authenticated %}
      {% if can_add %}
      <a class="btn btn-outline-primary" href="{% url 'nahtkurs:step_add' object.pk %}">{% trans 'Neuen Step hinzufügen' %}</a>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

project/lms_nahtkurs/templates/nahtkurs_course_home.html
{% extends "lms_nahtkurs_base.html" %}
{% load staticfiles i18n utils rules%}

{% block javascript %}
  {{ block.super }}
  {% if user.is_authenticated %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.5.1/Sortable.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>
  <script src="{{STATIC_URL}}lms_nahtkurs/js/lms_nahtkurs_course_home.js"></script>
  {% endif %}
  <script>
    var urlpath = "{% url 'nahtkurs:chapter_update_order' %}";
    var object_pk = '{{ object.pk }}';
</script>
{% endblock %}
{% block title %}
{{ object.title }}
{% endblock title %}

{% block course-title %}
{% include "nahtkurs_course-title.html" %}
{% endblock course-title %}

{% block content %}
{% has_perm 'lms_nahtkurs.change_nahtkurschapter' user object as can_change %}
{% has_perm 'lms_nahtkurs.delete_nahtkurschapter' user object as can_delete %}
{% has_perm 'lms_nahtkurs.add_nahtkurschapter' user object as can_add %}
<div class="d-none d-sm-block">
  <div class="container-fluid" style="background:url('{{ MEDIA_URL }}{{object.title_image}}'); background-repeat: no-repeat; background-position: top center; background-size: 100vw;">
    <div class="row no-gutters">
      <div class="col-12 col-md-10 offset-md-1">
        <div class="container-fluid">
          <div class="row no-gutters">
            <div class="col-12 col-md-10 offset-md-1 pt-3">
              <div class="bg-red px-4">
                <h1 class="course-heading">{{ object.title }} </h1>
                <h2 class="course-subtitle"> {{ object.subtitle }}</h2>
              </div>
            </div>
          </div>
          {% if object.content %}
          <div class="row markdown-content no-gutters">
            <div class="col-12 pt-3 col-md-10 offset-md-1">
              <div class="bg-white px-4">
                {{ object.content|markdownify|safe }}
                <h1 class="author-title pt-5">{% trans 'Die Autoren' %}</h1>
                <div class="row">
                {% for author in object.author.all %}
                  <div class="col-12 author-name">
                    {% if author.image %}
                    <img src="{{ MEDIA_URL }}{{ author.image }}">
                    {% endif %}
                    {{ author.name | markdownify | safe }}
                  </div>
                {% endfor %}
                </div>
                <!-- Autor Bild -->
              </div>
            </div>
          </div>
          {% endif %}
          <div class="row">
            <div class="col-12">
              {% with step=object.chapters.first.steps.first %}
              {% if step %}
              <div class="right-link pull-right bg-white-pn-link px-2 my-2 pb-2">
                <a href="{% url 'nahtkurs:step' object.slug object.pk step.chapter.slug step.chapter.pk step.slug step.pk%}" class="float-right arrow-link d-flex">
                  <div class="d-flex flex-center">
                  {{step}}<br>
                    <span class="step-type">{{ step.type_verbose }}</span>
                  </div>
                  <div class="arrow d-flex pl-4">
                    <i class="nmc-icon-next"></i>
                  </div>
                </a>
              </div>
              {% endif %}
              {% endwith %}
            </div>
          </div>
          {% if user.is_authenticated %}
          <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
              <div class="bg-white px-2">
              <h5>{% trans 'Kapitel' %}</h5>
                <table class="table table-sm">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>{% trans 'Titel' %}</th>
                      <th>{% trans 'Aktion' %}</th>
                    </tr>
                  </thead>
                  <tbody id="chapter-list">
                  {% for chapter in object.chapters.all %}
                  <tr data-id="{{ chapter.pk }}" class="chapter-list-item">
                    <td>
                      <i class="fa fa-bars handle" aria-hidden="true"></i>
                    </td>
                    <td>
                      <a href="{% url 'nahtkurs:chapter' object.slug object.pk chapter.slug chapter.pk %}">
                      {{ chapter.title }}
                      </a>
                    </td>
                    <td>
                      {% if user.is_authenticated %}
                      {% if can_change %}
                      <a href="{% url 'nahtkurs:chapter_edit' chapter.pk %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                        {% trans 'Bearbeiten' %}
                      </a>
                      {% endif %}
                      {% if can_delete %}
                      <a href="{% url 'nahtkurs:chapter_delete' chapter.pk %}">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                        {% trans 'Löschen' %}
                      </a>
                      {% endif %}
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% if user.is_authenticated %}
              {% if can_add %}
              <a class="btn btn-outline-primary" href="{% url 'nahtkurs:chapter_add' object.pk %}">{% trans 'Neues Kapitel hinzufügen' %}</a>
              {% endif %}
              {% endif %}
            </div>
          </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-sm-none">
  <div class="container-fluid" style="background:url('{{ MEDIA_URL }}{{object.title_image}}'); background-repeat: no-repeat; background-position: top center; background-size: 100vw;">
    <div class="row no-gutters">
      <div class="col-12 col-md-10 offset-md-1">
        <div class="container">
          <div class="row no-gutters">
            <div class="col-12 col-md-10 offset-md-1 pt-3">
              <div class="bg-red px-4">
                <h1 class="course-heading">{{ object.title }} </h1>
                <h2 class="course-subtitle"> {{ object.subtitle }} </h2>
              </div>
            </div>
          </div>
          {% if object.content %}
          <div class="row markdown-content no-gutters">
            <div class="col-12 pt-3 col-md-10 offset-md-1">
              <div class="bg-white px-4 py-2">
                {{ object.content|markdownify|safe }}
                {% endif %}
                <h1 class="author-title">Die Autoren</h1>
                <ul style="list-style-type: none; padding-left: 0;">
                {% for author in object.author.all %}
                  <li>
                    {{ author.name | markdownify | safe }}
                  </li>
                {% endfor %}
              </ul>
                <!-- Autor Bild -->
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              {% with step=object.chapters.first.steps.first %}
              {% if step %}
              <div class="right-link pull-right bg-white-pn-link px-2 my-2 pb-4">
                <a href="{% url 'nahtkurs:step' object.slug object.pk step.chapter.slug step.chapter.pk step.slug step.pk%}" class="float-right arrow-link d-flex">
                  <div class="d-flex flex-center">
                  {{step}}<br>
                    <span class="step-type">{{ step.type_verbose }}</span>
                  </div>
                  <div class="arrow d-flex pl-4">
                    <i class="nmc-icon-next"></i>
                  </div>
                </a>
              </div>
              {% endif %}
              {% endwith %}
            </div>
          </div>
          {% if user.is_authenticated %}
          {% if can_change %}
          <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
              <div class="bg-white px-2">
              <h5>{% trans 'Kapitel' %}</h5>
                <table class="table table-sm">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>{% trans 'Titel' %}</th>
                      <th>{% trans 'Aktion' %}</th>
                    </tr>
                  </thead>
                  <tbody id="chapter-list-small">
                  {% for chapter in object.chapters.all %}
                  <tr data-id="{{ chapter.pk }}" class="chapter-list-item">
                    <td>
                      <i class="fa fa-bars handle" aria-hidden="true"></i>
                    </td>
                    <td>
                      <a href="{% url 'nahtkurs:chapter' object.slug object.pk chapter.slug chapter.pk %}">
                      {{ chapter.title }}
                      </a>
                    </td>
                    <td>
                      {% if user.is_authenticated %}
                      {% if can_change %}
                      <a href="{% url 'nahtkurs:chapter_edit' chapter.pk %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                        {% trans 'Bearbeiten' %}
                      </a>
                      {% endif %}
                      {% if can_delete %}
                      <a href="{% url 'nahtkurs:chapter_delete' chapter.pk %}">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                        {% trans 'Löschen' %}
                      </a>
                      {% endif %}
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% if user.is_authenticated %}
              {% if can_add %}
              <a class="btn btn-outline-primary" href="{% url 'nahtkurs:chapter_add' object.pk %}">{% trans 'Neues Kapitel hinzufügen' %}</a>
              {% endif %}
              {% endif %}
            </div>
          </div>
          </div>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

project/lms_nahtkurs/templates/nahtkurs_course_list.html
{% extends "lms_nahtkurs_base.html" %}
{% load i18n utility_tags utils rules %}
{% block content %}

{% if user.is_authenticated %}

<h4> Courses </h4>

<div class="container">
  <div class="row">
    {% for course in nahtkurscourse_list %}
    <div class="col-3">
      <div class="card">
        <img class="card-img-top" src="{{MEDIA_URL}}{{course.title_image}}" alt="Card image cap">
        <div class="card-body">
          <h4 class="card-title">
             <a href="{% url 'nahtkurs:course' slug=course.slug pk=course.pk %}">
              {{ course.title }}
            </a>
          </h4>
          <h6 class="card-subtitle text-muted">
              {{ course.subtitle }}
          </h6>
          <p class="card-text">
            {{ course.content|truncatewords_html:30 }}
          </p>
          {% if user.is_authenticated %}
          {% has_perm 'lms_nahtkurs.change_NahtkursCourse' user course as can_change %}
          {% has_perm 'lms_nahtkurs.delete_NahtkursCourse' user course as can_delete %}

          {% if can_change %}
            <a class="btn btn-outline-primary" href="{% url 'nahtkurs:course_edit' course.pk %}">
              <i class="fa fa-pencil" aria-hidden="true"></i>
              {% trans 'Bearbeiten' %}
            </a>
          {% endif %}
          {% if can_delete %}
            <a class="btn btn-outline-danger" href="{% url 'nahtkurs:course_delete' course.pk %}">
              <i class="fa fa-trash" aria-hidden="true"></i>
              {% trans 'Löschen' %}
            </a>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% else %}
<div class="container">
  <div class="row no-gutters">
    <div class="col-12">
      <div>
        <p>HOME</p>
      </div>
      {% if user.is_authenticated %}
      {% include "nahtkurs_course_list.html" %}
      {% endif %}
    </div>
  </div>
</div>
{% endif %}


{% endblock %}