project/config/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from django.views import defaults as default_views

from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

# Add the files which shouldn't be internationalized
urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(
        r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'
    ),

    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Markdown processor
    url(r'^markdownx/', include('markdownx.urls')),
]

urlpatterns += i18n_patterns(
    # Examples:
    # url(r'^$', 'nmc_lms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Notice the expression does not end in $,
    # that happens at the myapp/url.py level
    # url(r'^tales/',include('lms_tales.urls', namespace='tales')),
    url(r'^', include('lms_tales.urls', namespace='tales')),
    url(r'^nahtkurs/', include('lms_nahtkurs.urls', namespace='nahtkurs')),
    url(r'^opos/', include('lms_opos.urls', namespace='opos')),
    # Example of redirect to site in specific hard coded language
    # url(r'^opos/', RedirectView.as_view(url='https://tales.nmc.unibas.ch/opos/en/',
    #                                    permanent=False), name='index'),

    # Tales
    url(r'^krank-ohne-ursache/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'krank-ohne-ursache', 'pk': '2'}
                                            )
                             ),
        name='redirect_krank-ohne-ursache'),
    url(r'^erasmus/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'erasmus-von-rotterdam', 'pk': '3'}
                                            )
                             ),
        name='redirect_erasmus'),
    url(r'^linear-algebra-ii/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'linear-algebra-ii', 'pk': '4'}
                                            )
                             ),
        name='redirect_linear-algebra-ii'),
    url(r'^conducting-psychological-research/',
        RedirectView.as_view(
            url=reverse_lazy(
                'tales:course',
                kwargs={'slug': 'conducting-psychological-research', 'pk': '6'}
                                            )
                            ),
        name='conducting-psychological-research'),


    url(r'^entrepreneurship-in-nonprofits/',
        RedirectView.as_view(url=reverse_lazy('tales:course',
                             kwargs={'slug': 'entrepreneurship-in-nonprofits', 'pk': '10'}  # NOQA
                                            )
                             ),
        name='redirect_entrepreneurship-in-nonprofits'),
    url(r'^base/', include('lms_base.urls', namespace='base')),

    url(r'^select2/', include('django_select2.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

project/lms_opos/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf import settings

from django.conf.urls import url
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView

from lms_opos import views


static_urls = [
    # markdown tutorial
    url(
        r'^markdown$',
        TemplateView.as_view(template_name='markdown.html'),
        name='markdown'
    ),
    url(
        r'^impressum$',
        TemplateView.as_view(template_name='impressum.html',),
        name='impressum'
    ),
    url(
        r'^about$',
        TemplateView.as_view(template_name='pages/opos_about.html',),
        name='about'
    ),
    url(
        r'^help$',
        TemplateView.as_view(template_name='help.html',),
        name='help'
    ),
]

course_urls = [
    # course list
    url(
        r'^$',
        views.CourseList.as_view(template_name='opos_course_list.html'),
        name='course_list'
    ),
    url(
        r'^course/add$',
        views.CourseCreate.as_view(),
        name='course_add'
    ),
    url(
        r'^course/edit/(?P<pk>\d+)$',
        never_cache(views.CourseUpdate.as_view()),
        name='course_edit'
    ),
    url(
        r'^course/delete/(?P<pk>\d+)$',
        views.CourseDelete.as_view(),
        name='course_delete'
    ),
    # course overview / chapter list
    url(
        r'^(?P<slug>[\w-]+)-(?P<pk>\d+)/$',
        views.CourseDetails.as_view(
            template_name='opos_course_home.html',
            ),
        name='course'
    ),
    url(
        r'^(?P<slug>[\w-]+)-(?P<pk>\d+)/kontakt$',
        views.CourseDetails.as_view(
            template_name='opos_kontakt.html',
            ),
        name='kontakt'
    ),
]

chapter_urls = [
    url(
        r'^chapter/add/(?P<course_pk>\d+)$',
        views.ChapterCreate.as_view(),
        name='chapter_add'
    ),
    url(
        r'^chapter/edit/(?P<pk>\d+)$',
        never_cache(views.ChapterUpdate.as_view()),
        name='chapter_edit'
    ),
    url(
        r'^chapter/delete/(?P<pk>\d+)$',
        views.ChapterDelete.as_view(),
        name='chapter_delete'
    ),
    # chapter overview / step list
    url(
        r'^(?P<course_slug>[\w-]+)-(?P<course_pk>\d+)/'
        r'(?P<slug>[\w-]+)-(?P<pk>\d+)/$',
        views.ChapterDetails.as_view(
            template_name='opos_chapter_home.html',
            ),
        name='chapter'
    ),
    url(
        r'^chapter_order$',
        views.chapter_update_order,
        name='chapter_update_order'
    ),
]

step_urls = [
    url(
        r'^step/add/(?P<chapter_pk>\d+)$',
        views.StepCreate.as_view(),
        name='step_add'
    ),
    url(
        r'^step/edit/(?P<pk>\d+)$',
        never_cache(views.StepUpdate.as_view()),
        name='step_edit'
    ),
    url(
        r'^step/delete/(?P<pk>\d+)$',
        views.StepDelete.as_view(),
        name='step_delete'
    ),
    # step
    url(
        r'^(?P<course_slug>[\w-]+)-(?P<course_pk>\d+)/'
        r'(?P<chapter_slug>[\w-]+)-(?P<chapter_pk>\d+)/'
        r'(?P<slug>[\w-]+)-(?P<pk>\d+)$',
        views.StepDetails.as_view(
            template_name='opos_step_home.html',
            ),
        name='step'
    ),
    url(
        r'^step_order$',
        views.step_update_order,
        name='step_update_order',
    ),
]

glossary_urls = [
    url(
        r'^glossar$',
        views.GlossaryView.as_view(template_name='opos_glossar.html',),
        name='glossar'
    ),
    url(
        r'^glossary/add/$',
        views.OposGlossaryItemCreate.as_view(),
        name='glossaryItem_add'
    ),
    url(
        r'^glossary/edit/(?P<pk>\d+)$',
        never_cache(views.OposGlossaryItemUpdate.as_view()),
        name='glossaryItem_edit'
    ),
    url(
        r'^glossary/delete/(?P<pk>\d+)$',
        views.OposGlossaryItemDelete.as_view(),
        name='glossaryItem_delete'
    ),
]


urlpatterns = static_urls + course_urls + chapter_urls + step_urls + glossary_urls  # NOQA

if settings.DEBUG:
    urlpatterns += [
        url(r'^404/$', views.NotFoundView.as_view()),
    ]

project/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

project/lms_opos/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

from lms_base.models import StepMixin, ChapterMixin, CourseMixin, GlossaryItemMixin  # NOQA


class OposStep(StepMixin):  # noqa 405
    chapter = models.ForeignKey(
            'OposChapter', null=True, related_name='steps'
            )

    def get_course(self):
        return self.chapter.course

    def get_absolute_url(self):
        return reverse('opos:step', args=[str(self.chapter.course.slug),
                                          str(self.chapter.course.id),
                                          str(self.chapter.slug),
                                          str(self.chapter.id),
                                          str(self.slug),
                                          str(self.id), ])

    def get_step_number(self):
        chapter_list = list(self.chapter.course.chapters.all()
                            .order_by('order'))
        chapter_num = str(chapter_list.index(self.chapter) + 1)
        step_list = list(self.chapter.steps.all().order_by('order'))
        step_num = str(step_list.index(self) + 1)
        index = chapter_num + "." + step_num
        return index

    def is_first_step_in_chapter(self):
        step_list = list(self.chapter.steps.all().order_by('order'))
        return step_list[0] == self

    def get_first_step_in_chapter(self):
        step_list = list(self.chapter.steps.all().order_by('order'))
        return step_list[0]

    def save(self, *args, **kwargs):
        if not self.chapter.steps.all():
            self.order = 0
        if self.order is None:
            self.order = max(step.order for step in
                             self.chapter.steps.all()) + 1
        super(OposStep, self).save(*args, **kwargs)


def step_directory_path(instance, filename):
    return '{0}/{1}/{2}/{3}'.format(
        instance.step.chapter.course.slug,
        instance.step.chapter.slug,
        instance.step.slug,
        filename)


@python_2_unicode_compatible
class OposStepFile(models.Model):
    title = models.CharField(max_length=70)
    step = models.ForeignKey('OposStep', related_name='files')
    file = models.FileField(upload_to=step_directory_path, max_length=255)

    def __str__(self):
        return self.title


class OposChapter(ChapterMixin):  # noqa 405

    course = models.ForeignKey(
            'OposCourse', null=True, related_name='chapters'
            )

    def get_course(self):
        return self.course

    def get_absolute_url(self):
        return reverse('opos:chapter', args=[str(self.course.slug),
                                             str(self.course.id),
                                             str(self.slug),
                                             str(self.id), ])

    def save(self, *args, **kwargs):
        if not self.course.chapters.all():
            self.order = 0
        if self.order is None:
            self.order = max(chapter.order for chapter in
                             self.course.chapters.all()) + 1
        super(OposChapter, self).save(*args, **kwargs)


class OposCourse(CourseMixin):  # noqa 405

    def get_course(self):
        return self

    def get_absolute_url(self):
        return reverse('opos:course', args=[str(self.slug),
                                            str(self.id), ])


class OposGlossaryItem(GlossaryItemMixin):  # noqa 405

    def __init__(self, *args, **kwargs):
        for f in self._meta.fields:
            if f.attname == "images":
                f.upload_to = "glossar"
        super(OposGlossaryItem, self).__init__(*args, **kwargs)

project/lms_opos/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms
from django.forms import ModelForm, widgets
from django.utils.datastructures import MultiValueDict  # NOQA

from extra_views import InlineFormSet

from lms_opos import widgets, models  # NOQA


class CourseForm(ModelForm):
    class Meta:
        model = models.OposCourse
        exclude = ['slug', 'owner', ]
        widgets = {
            'content': widgets.CustomisableMarkdownxWidget(),
            'content_de': widgets.CustomisableMarkdownxWidget(),
            'content_en': widgets.CustomisableMarkdownxWidget(),
            'author': widgets.CustomisableMarkdownxWidget(),
            'author_de': widgets.CustomisableMarkdownxWidget(),
            'author_en': widgets.CustomisableMarkdownxWidget(),
            'copyright': widgets.CustomisableMarkdownxWidget(),
            'copyright_de': widgets.CustomisableMarkdownxWidget(),
            'copyright_en': widgets.CustomisableMarkdownxWidget(),
            'course_contact': widgets.CustomisableMarkdownxWidget(),
        }


class UpdateCourseForm(CourseForm):
    title_image = forms.ImageField(required=False)


class ChapterForm(ModelForm):
    class Meta:
        model = models.OposChapter
        exclude = ['slug', 'order', 'course', ]
        widgets = {
            'content': widgets.CustomisableMarkdownxWidget(),
        }


class StepForm(ModelForm):
    class Meta:
        model = models.OposStep
        exclude = ['slug',
                   'order', 'chapter', ]
        widgets = {
            'content': widgets.CustomisableMarkdownxWidget(),
            'content_de': widgets.CustomisableMarkdownxWidget(),
            'content_en': widgets.CustomisableMarkdownxWidget(),
            'copyright': widgets.CustomisableMarkdownxWidget(),
            'copyright_de': widgets.CustomisableMarkdownxWidget(),
            'copyright_en': widgets.CustomisableMarkdownxWidget(),
        }


class GlossaryItemForm(ModelForm):
    class Meta:
        model = models.OposGlossaryItem
        exclude = []
        # fields = ['title', 'content', 'links', 'images', 'references']

        widgets = {
            'content': widgets.CustomisableMarkdownxWidget(),
            'references': widgets.CustomisableMarkdownxWidget(),
            'links': forms.SelectMultiple(),
        }


class FilesInline(InlineFormSet):
    model = models.OposStepFile
    fields = ['title', 'file']
    extra = 1

project/lms_opos/templates/home.html
{% extends "lms_opos_base.html" %}

project/lms_opos/templates/opos-title.html
<a class="course-title-link" href="{% url 'opos:course_list' %}">
  <p class="course-title d-flex">OPOS &nbsp;
  <span class="course-title-subtitle">Open Planet of Sound</span>
  </p>
</a>

project/lms_opos/templates/opos-with-sidebar-title.html
<a class="course-title-link" href="{% url 'opos:course_list' %}">
  <p class="course-title d-flex">OPOS &nbsp;
  <span class="course-title-subtitle">Open Planet of Sound</span>
  </p>
</a>

project/lms_opos/templates/opos_403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

project/lms_opos/templates/opos_500.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Internal Server Error{% endblock %}

{% block content %}
<h1>Ooops!!! 500</h1>
<h3>{% trans "Looks like something went wrong!" %}</h3>
<p>{% trans "We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing." %}</p>
{% endblock content %}

project/lms_opos/templates/opos_chapter-title.html
<p class="course-title d-flex">
<a href="{{ object.course.get_absolute_url }}">
  {{ object.get_course.title }} &nbsp;
  <span class="course-title-subtitle d-none d-sm-flex"> {{ object.course.subtitle }}</span>
</a>
</p>

project/lms_opos/templates/opos_chapter_home.html
{% extends "lms_opos_base.html" %}
{% load i18n rules %}
{% block javascript %}
  {{ block.super }}
  {% if user.is_authenticated %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.5.1/Sortable.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>
  <script src="{{STATIC_URL}}lms_opos/js/lms_opos_chapter_home.js"></script>
  {% endif %}
  <script>
    var urlpath = "{% url 'opos:step_update_order' %}";
    var object_pk = '{{ object.pk }}';
  </script>
{% endblock %}

{% block content %}
{% has_perm 'lms_opos.change_oposstep' user object.course as can_change %}
{% has_perm 'lms_opos.delete_oposstep' user object.course as can_delete %}
{% has_perm 'lms_opos.add_oposstep' user object.course as can_add %}

<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 pt-3">
      <h1 class="chapter-heading">{{ object.title }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-8 offset-md-2">
      <h5>{% trans 'Steps' %}</h5>
        <table class="table table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans 'Titel' %}</th>
              <th>{% trans 'Aktion' %}</th>
            </tr>
          </thead>
          <tbody id="step-list">
          {% for step in object.steps.all %}
          <tr data-id="{{ step.pk }}" class="step-list-item">
            <td>
              <i class="fa fa-bars handle" aria-hidden="true"></i>
            </td>
            <td>
              <a href="{% url 'opos:step' object.course.slug object.course.pk object.slug object.pk step.slug step.pk %}">
              {{ step.title }}
              </a>
            </td>
            <td>
              {% if user.is_authenticated %}
              {% if can_change %}
              <a href="{% url 'opos:step_edit' step.pk %}">
                <i class="fa fa-pencil" aria-hidden="true"></i>
                {% trans 'Bearbeiten' %}
              </a>
              {% endif %}
              {% if can_delete %}
              <a href="{% url 'opos:step_delete' step.pk %}">
                <i class="fa fa-trash" aria-hidden="true"></i>
                {% trans 'Löschen' %}
              </a>
              {% endif %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if user.is_authenticated %}
      {% if can_add %}
      <a class="btn btn-outline-primary" href="{% url 'opos:step_add' object.pk %}">{% trans 'Neuen Step hinzufügen' %}</a>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

project/lms_opos/templates/opos_course-title.html
{% load rules %}
<p class="course-title d-flex">{{ object.title }} &nbsp;
  <span class="course-title-subtitle d-none d-sm-flex">{{ object.subtitle }}</span>
  {% if user.is_authenticated %}
  {% has_perm 'lms_opos.change_oposcourse' user object as can_change_course %}
  {% if can_change_course %}
    <a href="{% url 'opos:course_edit' object.pk %}">
      <i class="fa fa-pencil" aria-hidden="true"></i>
    </a>
  {% endif %}
  {% endif%}
</p>

project/lms_opos/templates/opos_course_home.html
{% extends "lms_opos_base.html" %}
{% load staticfiles i18n utils %}
{% load rules %}
{% block javascript %}
  {{ block.super }}
  {% if user.is_authenticated %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.5.1/Sortable.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>
  <script src="{{STATIC_URL}}lms_opos/js/lms_opos_course_home.js"></script>
  {% endif %}
  <script>
    var urlpath = "{% url 'opos:chapter_update_order' %}";
    var object_pk = '{{ object.pk }}';
</script>
{% endblock %}

{% block course-title %}
{% include "opos-with-sidebar-title.html" %}
{% endblock course-title%}

{% block content %}
{% has_perm 'lms_opos.change_oposchapter' user object as can_change %}
{% has_perm 'lms_opos.delete_oposchapter' user object as can_delete %}
{% has_perm 'lms_opos.add_oposchapter' user object as can_add %}

<div class="d-none d-sm-block">
  <div class="container-fluid" style="background:url('{{ MEDIA_URL }}{{object.title_image}}'); background-repeat: no-repeat; background-position: top center; background-size: 100vw;">
    <div class="row no-gutters">
      <div class="col-12 col-md-10 offset-md-1">
        <div class="container-fluid">
          <div class="row no-gutters">
            <div class="col-12 col-md-10 offset-md-1 pt-3">
              <div class="bg-red px-4">
                <h1 class="module-heading">{{ object.title }} </h1>
                <h2 class="module-subtitle"> {{ object.subtitle }}</h2>
              </div>
            </div>
          </div>
          {% if object.content %}
          <div class="row markdown-content no-gutters">
            <div class="col-12 pt-3 col-md-10 offset-md-1">
              <div class="bg-white px-4">
                {{ object.content|markdownify|safe }}
              </div>
            </div>
          </div>
          {% endif %}
          <div class="row">
            <div class="col-12">
              {% with step=object.chapters.first.steps.first %}
              {% if step %}
              <div class="right-link pull-right bg-white-pn-link px-2 my-2 pb-2">
                <a href="{% url 'opos:step' object.slug object.pk step.chapter.slug step.chapter.pk step.slug step.pk%}" class="float-right arrow-link d-flex">
                  <div class="d-flex flex-center">
                  {{step}}<br>
                    <span class="step-type">{{ step.type_verbose }}</span>
                  </div>
                  <div class="arrow d-flex pl-4">
                    <i class="nmc-icon-next"></i>
                  </div>
                </a>
              </div>
              {% endif %}
              {% endwith %}
            </div>
          </div>
          {% if user.is_authenticated %}
          <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
              <div class="bg-white px-2">
              <h5>{% trans 'Kapitel' %}</h5>
                <table class="table table-sm">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>{% trans 'Titel' %}</th>
                      <th>{% trans 'Aktion' %}</th>
                    </tr>
                  </thead>
                  <tbody id="chapter-list">
                  {% for chapter in object.chapters.all %}
                  <tr data-id="{{ chapter.pk }}" class="chapter-list-item">
                    <td>
                      <i class="fa fa-bars handle" aria-hidden="true"></i>
                    </td>
                    <td>
                      <a href="{% url 'opos:chapter' object.slug object.pk chapter.slug chapter.pk %}">
                      {{ chapter.title }}
                      </a>
                    </td>
                    <td>
                      {% if user.is_authenticated %}
                      {% if can_change %}
                      <a href="{% url 'opos:chapter_edit' chapter.pk %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                        {% trans 'Bearbeiten' %}
                      </a>
                      {% endif %}
                      {% if can_delete %}
                      <a href="{% url 'opos:chapter_delete' chapter.pk %}">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                        {% trans 'Löschen' %}
                      </a>
                      {% endif %}
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% if user.is_authenticated %}
              {% if can_add %}
              <a class="btn btn-outline-primary" href="{% url 'opos:chapter_add' object.pk %}">{% trans 'Neues Kapitel hinzufügen' %}</a>
              {% endif %}
              {% endif %}
            </div>
          </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-sm-none">
  <div class="container-fluid" style="background:url('{{ MEDIA_URL }}{{object.title_image}}'); background-repeat: no-repeat; background-position: top center; background-size: 100vw;">
    <div class="row no-gutters">
      <div class="col-12 col-md-10 offset-md-1">
        <div class="container">
          <div class="row no-gutters">
            <div class="col-12 col-md-10 offset-md-1 pt-3">
              <div class="bg-red px-4">
                <h1 class="course-heading">{{ object.title }} </h1>
                <h2 class="course-subtitle"> {{ object.subtitle }} </h2>
              </div>
            </div>
          </div>
          {% if object.content %}
          <div class="row markdown-content no-gutters">
            <div class="col-12 pt-3 col-md-10 offset-md-1">
              <div class="bg-white px-4 py-2">
                {{ object.content|markdownify|safe }}
                {% endif %}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              {% with step=object.chapters.first.steps.first %}
              {% if step %}
              <div class="right-link pull-right bg-white-pn-link px-2 my-2 pb-4">
                <a href="{% url 'opos:step' object.slug object.pk step.chapter.slug step.chapter.pk step.slug step.pk%}" class="float-right arrow-link d-flex">
                  <div class="d-flex flex-center">
                  {{step}}<br>
                    <span class="step-type">{{ step.type_verbose }}</span>
                  </div>
                  <div class="arrow d-flex pl-4">
                    <i class="nmc-icon-next"></i>
                  </div>
                </a>
              </div>
              {% endif %}
              {% endwith %}
            </div>
          </div>
          {% if user.is_authenticated %}
          {% if can_change %}
          <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
              <div class="bg-white px-2">
              <h5>{% trans 'Kapitel' %}</h5>
                <table class="table table-sm">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>{% trans 'Titel' %}</th>
                      <th>{% trans 'Aktion' %}</th>
                    </tr>
                  </thead>
                  <tbody id="chapter-list-small">
                  {% for chapter in object.chapters.all %}
                  <tr data-id="{{ chapter.pk }}" class="chapter-list-item">
                    <td>
                      <i class="fa fa-bars handle" aria-hidden="true"></i>
                    </td>
                    <td>
                      <a href="{% url 'opos:chapter' object.slug object.pk chapter.slug chapter.pk %}">
                      {{ chapter.title }}
                      </a>
                    </td>
                    <td>
                      {% if user.is_authenticated %}
                      {% if can_change %}
                      <a href="{% url 'opos:chapter_edit' chapter.pk %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                        {% trans 'Bearbeiten' %}
                      </a>
                      {% endif %}
                      {% if can_delete %}
                      <a href="{% url 'opos:chapter_delete' chapter.pk %}">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                        {% trans 'Löschen' %}
                      </a>
                      {% endif %}
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% if user.is_authenticated %}
              {% if can_add %}
              <a class="btn btn-outline-primary" href="{% url 'opos:chapter_add' object.pk %}">{% trans 'Neues Kapitel hinzufügen' %}</a>
              {% endif %}
              {% endif %}
            </div>
          </div>
          </div>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}